### ISSUE TITLE
fix for ipywidgets-8

### ISSUE THREAD

**Issue by pjaol** [ieriii/spacy-annotator#14]
Awesome widget @ieriii !!
Just got this to work on Vertext AI Workbench and ipywidgets-8 with a single line change in #13 

Don't know why but display_html would go blank after the first iteration, switching it to use just display solves it.

**Comment by ieriii** [comment]
THank you @pjaol! Very helpful! I'll add your suggestion soon.

**Comment by ieriii** [comment]
Thank you. This has been fixed a804b68.
